### ISSUE TITLE
[BUG] gulp-eslint does not resolve ESLints rule lib completely

### ISSUE THREAD

**Issue by tillyboy** [flaganalytics/gulp-eslint#28]
This plugin seems not to include some rules from ESLint. I verified that running ESLint via `npx eslint src` runs just fine.

#### How to reproduce
1. Enable any or all of the rules:
  - `no-promise-executor-return`
  - `no-unreachable-loop`
  - `no-useless-backreference`
  - `default-case-last`
2. Try to use gulp to lint a file

#### How to fix it (when using `gulp-eslint`)
Breaks:
```js
...
  .pipe(eslint())
...
```

Works:
```js
...
  .pipe(eslint({ rulePaths: ["node_modules/eslint/lib/rules"] }))
...
```

#### Versions

gulp: 4.0.2
gulp-cli: 2.3.0
gulp-eslint: 6.0.0
ESLint: 7.9.0
node: 14.12.0
npm: 6.14.7

**Comment by doamatto** [comment]
Thanks for reporting this bug! I'll do my best to get it resolved ASAP, but feel free to make a PR for Hacktober if you'd like.

**Comment by tillyboy** [comment]
This might actually be a bug in `adametry/gulp-eslint`, I got confused because there are multiple of those on github. On the other hand, Adametry seems to have abondened his plugin. Do I assume correctly that you have forked the project from him?

**Comment by tillyboy** [comment]
I quickly tried figuring how to do it and failed, but have another PR in the making for you.

**Comment by doamatto** [comment]
> On the other hand, Adametry seems to have abondened his plugin. Do I assume correctly that you have forked the project from him?

Yup this is a fork merging a lot of the PRs and resolving a handful of issues from the, what I also assume as, Adametry's abandoned plugin.

> have another PR in the making for you.
Awesome! When I see the notification on GitHub, I'll do a quick review and merge if everything looks ay-okay!

**Comment by tillyboy** [comment]
I just tried this with this plugin instead of the old one. Works out of the box. I guess this version should become the default, and the error originated from some dependency deprecation.

**Comment by doamatto** [comment]
Yeah, there were **a lot** of deprecated and out of date dependencies, but everything should run much smoother.
